CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS leaderboard (
  id BIGSERIAL PRIMARY KEY,
  playerName TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  contestType TEXT NOT NULL,
  level INTEGER NOT NULL,
  contentMode TEXT NOT NULL,
  duration INTEGER,
  taskTarget INTEGER,
  score DOUBLE PRECISION NOT NULL,
  accuracy DOUBLE PRECISION NOT NULL,
  cpm DOUBLE PRECISION NOT NULL,
  mistakes INTEGER NOT NULL,
  tasksCompleted INTEGER NOT NULL,
  timeSeconds DOUBLE PRECISION NOT NULL,
  maxStreak INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS vocab_packs (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  packType TEXT NOT NULL,
  items TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 0,
  createdAt TEXT NOT NULL
);
